project_id = "supiwygxypfqjzoqmlaq"

[functions.midtrans-order-settings]
verify_jwt = false

[functions.midtrans-order-charge]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.super-admin-midtrans-payments]
verify_jwt = false

[functions.super-admin-xendit-secret]
verify_jwt = false

[functions.order-payment-provider]
verify_jwt = false

[functions.xendit-invoice-create]
verify_jwt = false

[functions.super-admin-paypal-settings]
verify_jwt = false

[functions.super-admin-paypal-secret]
verify_jwt = false

[functions.paypal-order-settings]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false